# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e83aa0136476ddf6b71f5102f68f64183fdabb882d98f46aeee9a5a1ff75f0b5d6fdb96ff9f804c368e182c0d43d78b8f4d0347280a332e233b0edd027c96e42

test:
  secret_key_base: 345edb4e73654ab3bdb1e88c995f9a9c8c639a1e231a50309f38aac350639aec85121fdd9c0389e9cfdd5db6facd07e7870f0bddb3457f67cf049c7b7bc1aff0

staging:
  secret_key_base: 345edb4e73654ab3bdb1e88c995f9a9c8c639a1e231a50309f38aac350639aec85121fdd9c0389e9cfdd5db6facd07e7870f0bddb3457f67cf049c7b7bc1aff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1231
