# config/settings.yml
defaults: &defaults
  server_uri: "http://115.28.132.220:81"

  default_title: "卡拉丁 | 上门汽车保养"
  meta_keywords: "卡拉丁, 上门汽车养护服务, 汽车保养, 汽车"
  meta_description: "卡拉丁为广大车主提供优质、便捷、安全的上门汽车养护服务。服务热线：400-006-8181"

  baidu_ak: "227c2a3806aae1804f15cff021674ef9"

  aes_key: "Gr8c6Up6553ZjO9l"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  server_uri: "http://intranet.kalading.com"
