# config/settings.yml
defaults: &defaults
  server_uri: "http://115.28.132.220:81"

  weixin_api: "https://api.weixin.qq.com/cgi-bin/"

  weixin_appid: "wxde94f73ba776b7df"
  weixin_appsecret: "e2657f01bdab7656f61d9b92717caa75"

  weixin_token: "abcdefg"
  weixin_secret: "Mn8HHt0phlqnoCq7dMaJuvPbUi_sAajJ"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  server_uri: "http://intranet.kalading.com"
