# config/settings.yml
defaults: &defaults
  server_uri: "http://121.42.155.108:81"

  default_title: "卡拉丁 | 上门汽车保养"
  meta_keywords: "卡拉丁, 上门汽车养护服务, 汽车保养, 汽车"
  meta_description: "卡拉丁为广大车主提供优质、便捷、安全的上门汽车养护服务。服务热线：400-006-8181"

  baidu_ak: "227c2a3806aae1804f15cff021674ef9"

  # roles
  administrators:
    - "15666300899" # congteng
    - "15901003277" # coder
    - "17710191420" # jianan
    - "18612621540" # shooter
    - "17600810530" # river
    - "18611494397" # zhoumin

  editors:
    - "13810313046" # sally

development:
  <<: *defaults
  #server_uri: "http://intranet.kalading.com"

test:
  <<: *defaults

staging:
  <<: *defaults
  domain: "http://staging.kalading.com"

production:
  <<: *defaults
  server_uri: "http://intranet.kalading.com"
  domain: "http://kalading.com"
